### ISSUE TITLE
Problem with decimal points in countries where point is not used as decimal seperator

### ISSUE THREAD

**Issue by joyrider3774** [Lacro59/playnite-systemchecker-plugin#16]
Hey,

It seems the plugin has problems interpreting decimal points on my system. An example game would be destiny 2. It says on the site 67.9 GB yet in your plugin it says 679GB. I'm not sure if my regional settings are to blame or not but in my country "," comma is used as decimal seperator and "." usually as thousand seperator. If you use regional settings data for decimal point in your plugin it might not detect this correctly.

![image](https://user-images.githubusercontent.com/10714776/130888515-a055e40f-c03e-40db-b6ee-b43738faf5ca.png)

**Comment by Lacro59** [comment]
Have you try with the v2.0?

**Comment by joyrider3774** [comment]
hi Lacro59,

Just tested with V2.0 in playnite 9, same problem exists (even when refreshing data)

**Comment by Lacro59** [comment]
I am having trouble reproducing the problem.
I am using the decimal separator "," and I don't have this problem.
I will compile a special version for more logging.
