### ISSUE TITLE
SystemChecker causes Playnite to crash on startup

### ISSUE THREAD

**Issue by darklinkpower** [Lacro59/playnite-systemchecker-plugin#19]
![image](https://user-images.githubusercontent.com/1389286/133399314-292dd66a-79f3-4962-88bf-906a2ec77049.png)

[playnite.log](https://github.com/Lacro59/playnite-systemchecker-plugin/files/7168337/playnite.log)

[extensions.log](https://github.com/Lacro59/playnite-systemchecker-plugin/files/7168338/extensions.log)

**Comment by Lacro59** [comment]
Can you try this version?
[playnite-systemchecker-plugin_2_0.zip](https://github.com/Lacro59/playnite-systemchecker-plugin/files/7277894/playnite-systemchecker-plugin_2_0.zip)

**Comment by darklinkpower** [comment]
Still happening in that build

![image](https://user-images.githubusercontent.com/1389286/135868961-27fd3541-8a82-44e9-a788-3e0c6be551b6.png)

```
04-10 09:29:11.104|WARN |GameActivity#Common:File C:\Games\Playnite\Extensions\playnite-gameactivity-plugin\Resources\Controls\ListExtendStyle.xaml not find
04-10 09:29:12.073|DEBUG|SuccessStory#Downloader:Downloading string content from https://steamcommunity.com/profiles/76561198025294991/ using System.Text.UTF8Encoding encoding.
04-10 09:29:12.891|WARN |SystemChecker#ItemCollection`1:Skipping non-id collection item C:\Games\Playnite\ExtensionsData\e248b230-6edf-41ea-a3c3-7861fa267263\SystemChecker\pc.json
04-10 09:29:13.424|DEBUG|SuccessStory#Downloader:Downloading string content from https://steamcommunity.com/id/darklinkpower using System.Text.UTF8Encoding encoding.
04-10 09:29:14.131|WARN |SuccessStory#GenericAchievements:Bad Steam configuration
04-10 09:29:17.696|ERROR|GameActivity#Common:Error on Win32_VideoController|D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\playnite-plugincommon\CommonPluginsShared\LocalSystem.cs|163
System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en CommonPluginsShared.LocalSystem.GetPcInfo(Boolean WithDiskInfos) en D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\playnite-plugincommon\CommonPluginsShared\LocalSystem.cs:línea 163
```

**Comment by Ohkami** [comment]
same thing for me :
[Systemchecker.zip](https://github.com/Lacro59/playnite-systemchecker-plugin/files/7359622/Systemchecker.zip)

**Comment by joyrider3774** [comment]
@Ohkami @Ohkami if you got powershell installed could you post output of `Get-WmiObject -Query "select * from Win32_VideoController"`

**Comment by Lacro59** [comment]
I deleted this variable which is not used ...
