### ISSUE TITLE
Integration button not showing even when it has been enabled in settings

### ISSUE THREAD

**Issue by darklinkpower** [Lacro59/playnite-systemchecker-plugin#3]
![imagen](https://user-images.githubusercontent.com/1389286/88219838-c76fb880-cc27-11ea-935d-0da3adc1755c.png)

**Comment by shakeyourbunny** [comment]
It is also not visible if you are using SteamNite.

**Comment by Lacro59** [comment]
Resolved with current version and for custom theme, it's not supported in native.
