### ISSUE TITLE
Doesn't detect discrete graphics

### ISSUE THREAD

**Issue by AnAvidEditor** [Lacro59/playnite-systemchecker-plugin#37]
Hi there,

Great plugin! I'm on playnite 9.19 w/ plugin version 2.1.2. When I run the check it only detects my Intel UHD Graphics 620 and not my discrete card NVIDIA Geforce MX150. I'm on a Lenovo 14s-ikb laptop. Is there something I can adjust to fix this? Thanks!

![Doesn't detect discrete Graphics](https://user-images.githubusercontent.com/68677230/192341580-7ef1515f-97b8-4d7f-b6f3-aad27d665d43.PNG)

**Comment by King-0f-Hero** [comment]
I have the same problem only with "AMD Radeon(TM) Graphics" showing instead of my Nvidia RTX 3050 Ti Laptop.
This sadly undermines the whole purpose of the extension which surely would be great otherwise.
Hope this gets fixed soon.
Thanks in advance for all your efforts Lacro59!

![image](https://user-images.githubusercontent.com/93925732/211065897-23508cf5-fa69-49f7-9a74-ff2d3ad5b912.png)

**Comment by soaringjupiter** [comment]
I have the same problem as well, with Nvidia GTX 1660 Ti, which it does not pick up, instead recognising only my integrated graphics, making me fail the recommended when I should have passed

![image](https://user-images.githubusercontent.com/83482921/236680249-d8dc8e26-068f-415c-a12a-c04691b8f241.png)

**Comment by stepan323446** [comment]
> Same issue here and I tried removing the intel graphic card from the configuration file but it seems to load it again.

He's already abandoned the project. Same problem. I'll try to create it myself - as soon as I create it, I'll write to everyone

**Comment by KidesLeo** [comment]
> He's already abandoned the project. Same problem. I'll try to create it myself - as soon as I create it, I'll write to everyone

I'll try to fork and add a fix, whoever does it first I guess.

**Comment by Slippy2k** [comment]
Has anyone now fixed the problem?

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-plugincommon/commit/594e207f1850e26de2c9fb1b0e4a7945908f5f7a
