### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Katanalx** [Lacro59/playnite-systemchecker-plugin#38]
Hello, 

I'm new to Github, I don't know if I'm in the right place to ask questions.
I have a problem with system checker. It always gives the message "The reference of object wasn't defined as an instance of an object" (I'm translating from Portuguese so maybe is not quite like this in English).
I cancelled the search as soon as I saw the error but it gives the same error if I let the search finish. Also, looks like is at different times in the progression. 
Again, I'm sorry if this is not the right place. Please tell me where it is so I can send you this.
Thanks in advance.
[SystemChecker_2022-11-29.zip](https://github.com/Lacro59/playnite-systemchecker-plugin/files/10116498/SystemChecker_2022-11-29.zip)

**Comment by Katanalx** [comment]
Hello again! I tested a little bit by doing a system check in blocks of games (I have 2000+ I'm on the letter N) and found  out that the following games give the error:
3DMark - Steam
Beyond Good and Evil - Ubisoft
Clinically death - Steam
C & C : Red Alert 3 Uprising - Steam
Crazy Taxi - Steam
Draw a Stickman: EPIC - Steam
GTA: San Andreas - Steam
NeonHat - Playstation

I hope it helps

**Comment by Katanalx** [comment]
I run the rest of my collection:
Sonic & All Stars Racing collection - Steam
Sonic Adventure DX - Steam
Sonic & All Stars Racing DLC - Steam
Sonic & All Stars Racing Transformed Collection
Wallace & Gromit ep. 1 to 4
Wallace & Gromit Grand Adventure
XCOM: Apocalypse
X-COM: UFO Defense
If you want I can make individual reports for each error
Thank you for you excellent effort

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-plugincommon/commit/95b3845caf088730d1a9c02d8dccbba30f0cfd73
