### ISSUE TITLE
Incorrectly fetching requirements data does not inform user of mismatching title

### ISSUE THREAD

**Issue by sunsetHue** [Lacro59/playnite-systemchecker-plugin#45]
## Bug Description
SystemChecker currently fetches the closest match when it finds no exact titles. When this happens, there is no selection or notification to the user that this happened until they check the listed source in the pop-up box or that this data might be incorrect.

## To Reproduce
1. Add "Eternum"
2. Refresh data with SystemChecker
3. Data fetched incorrectly as "Eternum EX"

## Extensions log
_No relevant data excluding regular fetch info._

## Screenshots
![image](https://github.com/Lacro59/playnite-systemchecker-plugin/assets/171299814/aec02d17-fc46-4d5e-a41a-7d628383477e)

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-plugincommon/commit/935eff876daed45624a4d2a232380f6d89b0447f
